. "$PSScriptRoot\Functions\GenXdev.Console.Vlc\Open-VlcMediaPlayer.ps1"
. "$PSScriptRoot\Functions\GenXdev.Console.Vlc\Open-VlcMediaPlayerLyrics.ps1"
. "$PSScriptRoot\Functions\GenXdev.Console.Vlc\Start-VlcMediaPlayerNextInPlaylist.ps1"
. "$PSScriptRoot\Functions\GenXdev.Console.Vlc\Start-VlcMediaPlayerPreviousInPlaylist.ps1"
. "$PSScriptRoot\Functions\GenXdev.Console.Vlc\Switch-VlcMediaPlayerMute.ps1"
. "$PSScriptRoot\Functions\GenXdev.Console.Vlc\Switch-VLCMediaPlayerPaused.ps1"
. "$PSScriptRoot\Functions\GenXdev.Console.Vlc\Switch-VlcMediaPlayerRepeat.ps1"
